### ISSUE TITLE
Error while building image.

### ISSUE THREAD

**Issue by Ayush2832** [nigelpoulton/psweb#19]
Hello @nigelpoulton,

I encountered an issue while building the docker image, which I have attached a photo of. However, I was able to resolve the issue by making changes to the Dockerfile and using `From node: alpine`. 
I am curious to know if this is a good practice. Additionally, if you have any input on this issue, I would greatly appreciate it.

Thank you.

![WhatsApp Image 2024-02-25 at 19 36 33_4b70e40e](https://github.com/nigelpoulton/psweb/assets/98541105/16fd4581-904c-4bfb-9ab7-7c164c513b6f)

**Comment by nigelpoulton** [comment]
Hi @Ayush2832 

can you let me know exactly which part of which video course or chapter of which book so i can look into this. 

If you could provide system info (e.g. Docker Desktop v4.27 on MacOS on Arm...) a full copy of your Dockerfile in case it's different to the one in the repo. If you're running a VPN etc. 

👍👍

**Comment by Ayush2832** [comment]
Thanks for your time @nigelpoulton 
1. I was reading your book preview (https://www.google.co.in/books/edition/_/DicGEAAAQBAJ?hl=en&gbpv=1) and on page number 27, I was doing the exercise. 

2. The docker version I am using is mentioned in the photo

<img src="https://github.com/nigelpoulton/psweb/assets/98541105/41f1366e-85c5-44dc-b68e-21ef3955e225" alt="Description" width="500" height="500">

3.  Dockerfile

![Screenshot 2024-02-25 223152](https://github.com/nigelpoulton/psweb/assets/98541105/caf6f342-7749-4c02-b49c-4b7aafd75bd0)


"PS: I am currently learning about Docker and I am very new to this field. I believe that the error I encountered may have been due to me following the wrong steps. I apologize for any mistakes I may have made. I would greatly appreciate it if you could provide me with some guidance for the future."

**Comment by nigelpoulton** [comment]
I'll try and take a look at this tomorrow and see if I can reproduce the issue on my machine.

**Comment by nigelpoulton** [comment]
OK I've actually done a quick bit of testing and it works on my machine with the following `Dockerfile` using the `alpine:latest` image:

```
FROM alpine
RUN apk add --update nodejs npm curl
COPY . /src
WORKDIR /src
RUN npm install --loglevel silly
EXPOSE 8080
ENTRYPOINT ["node", "./app.js"]
```

I get this with the build. Basically it installs the packages as expected.

```
$ docker build -t test .
[+] Building 29.2s (10/10) FINISHED                                                                              docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                             0.0s
 => => transferring dockerfile: 357B                                                                                             0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                 1.2s
 => [internal] load .dockerignore                                                                                                0.0s
 => => transferring context: 659B                                                                                                0.0s
 => CACHED [1/5] FROM docker.io/library/alpine:latest@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b    0.0s
 => => resolve docker.io/library/alpine:latest@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b           0.0s
 => [internal] load build context                                                                                                0.0s
 => => transferring context: 242B                                                                                                0.0s
 => [2/5] RUN apk add --update nodejs npm curl                                                                                  14.0s
 => [3/5] COPY . /src                                                                                                            0.0s
 => [4/5] WORKDIR /src                                                                                                           0.0s
 => [5/5] RUN npm install --loglevel silly                                                                                      11.5s
 => exporting to image                                                                                                           2.3s
 => => exporting layers                                                                                                          1.8s
 => => exporting manifest sha256:6197abe98dae7a5696a9c06cbbbfa186171f4a8404c807cbf083bdd7224b0ca9                                0.0s
 => => exporting config sha256:403a1aeafd9790f2ffe36558fda095369c0ca83504f3c3d6d2cfa8d7d8f21b99                                  0.0s
 => => exporting attestation manifest sha256:f7c6308e55511b5939810c6fbe66008e79d51aae473d65f310458dd2f96816e2                    0.0s
 => => exporting manifest list sha256:df5f10fc95fc1ad78494a995bdd57f0f0a9a78762ec0a4b2362f2a53e69ebe28                           0.0s
 => => naming to docker.io/library/test:latest                                                                                   0.0s
 => => unpacking to docker.io/library/test:latest                                                                                0.5s
```

So I've no idea why you were getting the issues with your initial build. I've once seen a similar issue accessing packages when behind my personal Express VPN.

Either way, it's fine to use the `node` image or the `node:alpine` image. But with those you probably don't need the `RUN apk add --update nodejs npm` as node images probably have both of these already installed.

HTH

**Comment by Ayush2832** [comment]
"Okay, thank you for taking the time to address this issue."👍
