### ISSUE TITLE
ERROR: unsatisfiable constraints

### ISSUE THREAD

**Issue by ellismendez** [nigelpoulton/psweb#2]
Hi,
Trying to build the image as per the book instructions gives an error:
$docker image build -t test:latest .

Sending build context to Docker daemon  74.75kB
Step 1/8 : FROM alpine
 ---> 3fd9065eaf02
Step 2/8 : LABEL maintainer="nigelpoulton@hotmail.com"
 ---> Using cache
 ---> 11f318a672f1
Step 3/8 : RUN apk add --update nodejs nodejs-npm
 ---> Running in 4e758412be23
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.70c88391.tar.gz: No such file or directory
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.7/community: operation timed out
WARNING: Ignoring APKINDEX.5022a8a2.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  nodejs (missing):
    required by: world[nodejs]
  nodejs-npm (missing):
    required by: world[nodejs-npm]
The command '/bin/sh -c apk add --update nodejs nodejs-npm' returned a non-zero code: 2

**Comment by Ghayyas** [comment]
Same Issue with me :confused:

**Comment by mahesh197** [comment]
Disable your firewall using "sudo systemctl disable firewalld", restart your pc and check.

**Comment by nigelpoulton** [comment]
Closing due to age. Apologies that I didn't see this earlier. If it's still an issue, open a new issue and I'll look into it. Cheers.
