### ISSUE TITLE
Unable to build the image.

### ISSUE THREAD

**Issue by nagesh21** [nigelpoulton/psweb#5]
Hi,
 I am new to Docker world i am trying to build the image and followed the steps as showed in the video. But i am getting below error : 

Step 3/8 : RUN apk add --update node.js nodejs-npm
 ---> Running in 6f8d572825d1
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  node.js (missing):
    required by: world[node.js]
The command '/bin/sh -c apk add --update node.js nodejs-npm' returned a non-zero code: 1

And my Dockerfile looks like this : 
FROM alpine
LABEL maintainer ="nmohan211@outlook.com"
RUN apk add --update nodejs nodejs-npm
COPY . /src
WORKDIR /src
RUN npm install
EXPOSE 8080
ENTRYPOINT [ "node","./app.js" ]

**Comment by alexlx1797** [comment]
you need execute "systemctl restart docker"

**Comment by mahesh197** [comment]
Disable your firewall using "sudo systemctl disable firewalld", restart your pc and check.

**Comment by nigelpoulton** [comment]
Closing due to age. Apologies that I didn't see this earlier. If it's still an issue, open a new issue and I'll look into it. Cheers.
